apiVersion: v1
kind: Pod
metadata:
  name: spark-template
spec:
  containers:
    - volumeMounts:
        - name: spark-app
          mountPath: /opt/spark/apps
  volumes:
    - name: spark-app
      configMap:
        name: spark-app
